site_name: Thinking in Blockchain
extra_css: [css/extra.css]

pages:
- 前言: index.md
- 去中心化(Decentralization): decentralization.md
- Hyperledger(超级账本): hyperledger.md
- Factom(公证通): factom.md
- Ripple(瑞波币): ripple.md
- 'SCII区块链实验室':
  - '调研报告':
    - '熊猫绿能': 'report/PandaGreen.md'
  - '每周汇总':
    - '20180416': 'weekly/Weekly.20180416.md'
